# Generated by Django 3.1.1 on 2020-10-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovry',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
