# Generated by Django 3.1.1 on 2020-10-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORM', '0003_author_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='type',
            new_name='generType',
        ),
    ]
