# Generated by Django 3.1.1 on 2020-10-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=125, verbose_name='Student Name')),
                ('smob', models.CharField(max_length=10, verbose_name='Mobile no.')),
                ('saddress', models.CharField(max_length=225, verbose_name='Address')),
                ('pin', models.IntegerField(max_length=6, verbose_name='Pin Code')),
            ],
        ),
    ]
