# Generated by Django 3.1.1 on 2020-10-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataTable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='pin',
            field=models.IntegerField(verbose_name='Pin Code'),
        ),
    ]
