# Generated by Django 3.1.1 on 2020-09-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100, verbose_name='Client Name')),
                ('cmobno', models.CharField(max_length=10, verbose_name='Mobile No')),
                ('address', models.CharField(max_length=125, verbose_name='Address')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pin')),
            ],
        ),
    ]
